name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Update this if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Pylint and Pytest  # ✅ FIX: Ensure pytest is installed
        run: pip install pylint pytest

      - name: Run PyLint
        run: pylint math_operations.py

      - name: Run Unit Tests
        run: pytest tests/
